# Generated by Django 5.2.8 on 2025-12-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disabled', 'Disabled')], default='pending', help_text='User account status', max_length=20),
        ),
    ]
