# Generated by Django 5.2.8 on 2025-12-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0006_smslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='recipients',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
